// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tarea2IF3000;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Tarea2IF3000.Usuarios;

/************************************************************/
/**
 * 
 */
public class Autor extends Usuarios {

	public Autor(String nombreUnico, String contraseña, String nombre, String tipoIdentificacion, int identificacion) {
		super(nombreUnico, contraseña, nombre, tipoIdentificacion, identificacion);
	
	}

	
	ArrayList <Autor> autorList = new ArrayList <Autor>();
	

	/**
	 * 
	 * @return 
	 */
	public void ListaObrasEscritas() {

		
	}
	public void ListaAutores(Autor au) {
		
		autorList.add(au);
		JOptionPane.showMessageDialog(null, "Autor agregado con exito");
	
	}
	public boolean encuentraAutor(String nombre) {
		//for(int i =0;i<autorList.size();i++)
	      
		
		return false;
		
		
		
	}
	
	
};
