// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tarea2IF3000;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Tarea2IF3000.Usuarios;

/************************************************************/
/**
 * 
 */
public class Bibliotecario extends Usuarios {
	public Bibliotecario(String nombreUnico, String contraseña, String nombre, String tipoIdentificacion,
			int identificacion) {
		super(nombreUnico, contraseña, nombre, tipoIdentificacion, identificacion);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private String Libros;
	/**
	 * 
	 */
	private String Autores;
	/**
	 * 
	 */
	private String usuarios;

	/**
	 * 
	 * @return 
	 */
	public boolean Agregar() {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean Quitar() {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean Modificar() {
		return false;
	}

	public String getLibros() {
		return Libros;
	}

	public void setLibros(String libros) {
		Libros = libros;
	}

	public String getAutores() {
		return Autores;
	}

	public void setAutores(String autores) {
		Autores = autores;
	}

	public String getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(String usuarios) {
		this.usuarios = usuarios;
	}
	
	public void ListaLibros(String libro) {
		ArrayList <String> LibrosList = new ArrayList <String>();
		LibrosList.add(libro);
		JOptionPane.showMessageDialog(null, "Libro agregado con exito");
		
	}
	
	
};
