// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tarea2IF3000;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Tarea2IF3000.Usuarios;

/************************************************************/
/**
 * 
 */
public class Usuario extends Usuarios {
	public Usuario(String nombreUnico, String contraseña, String nombre, String tipoIdentificacion,
			int identificacion) {
		super(nombreUnico, contraseña, nombre, tipoIdentificacion, identificacion);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 * @return 
	 */
	public void ListaObrasPrestadas(Usuario us) {
		
		
	}
	
	public void ListaUsuarios(Usuario us) {
		ArrayList <Usuario> autorList = new ArrayList <Usuario>();
		autorList.add(us);
		JOptionPane.showMessageDialog(null, "Usuario agregado con exito");
		
	}
	
	
	
};
